# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfile
      target: backend
    container_name: mollama_backend
    restart: unless-stopped
    volumes:
      - ./src/backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - proxy_data:/data
    ports:
      - "11111:11111"
    networks:
      - network
    command: uvicorn main:app --host 0.0.0.0 --port 11111 --reload --reload-dir /app

  frontend:
    build:
      context: .
      dockerfile: ./dockerfile
      target: frontend
    container_name: mollama_frontend
    restart: unless-stopped
    volumes:
      - ./src/frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "22222:22222"
    networks:
      - network
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 22222

networks:
  network:
    driver: bridge

volumes:
  proxy_data:
  frontend_node_modules: